package kresbilgisistemi;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author EmircanKirez
 */
public class AddEnrollmentScreen extends javax.swing.JFrame {
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
     
    public AddEnrollmentScreen() {
        initComponents();
        changeLblPriceInfo();
    }
    
    public void addEnrollment(){
        try{
            if(txtChildName.getText().equals("") || txtChildSurname.getText().equals("") || fTxtBirthdate.getText().contains(" ") || txtParentName.getText().equals("")
                    || fTxtPhone.getText().contains(" ")){
                JOptionPane.showMessageDialog(this, "Bütün bilgileri eksiksiz giriniz.");
            }else{
                MainScreen.connection.setAutoCommit(false); // aşağıdaki her bir query'nin çalışması lazım. O yüzden elle commit yapılır.
                
                PreparedStatement preparedStatement = MainScreen.connection.prepareStatement("INSERT INTO child VALUES  (nextval('childSeq'), ?, ?, ?)");
                preparedStatement.setString(1, txtChildName.getText());
                preparedStatement.setString(2,  txtChildSurname.getText());
                java.util.Date utilDate = formatter.parse(fTxtBirthdate.getText());
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                preparedStatement.setDate(3, sqlDate);
                preparedStatement.executeUpdate();
                
                preparedStatement = MainScreen.connection.prepareStatement("SELECT MAX(id) FROM child");
                ResultSet resultSet = preparedStatement.executeQuery();
                int childId = 0;
                while(resultSet.next()){
                    childId = resultSet.getInt(1);
                }
                
                preparedStatement = MainScreen.connection.prepareStatement("INSERT INTO enrollment VALUES (?, ?, ?, (SELECT EXTRACT(YEAR FROM age(current_date, birthdate)) FROM child WHERE id = ?))");
                preparedStatement.setInt(1, childId);
                preparedStatement.setString(2, (String) cBoxPaymentType.getSelectedItem());
                preparedStatement.setString(3, (String) cBoxEnrollmentType.getSelectedItem());
                preparedStatement.setInt(4, childId);
                preparedStatement.executeUpdate();
                
                
                preparedStatement = MainScreen.connection.prepareStatement("INSERT INTO parent (childId, fname, lname, gender, phone) VALUES (?, ?, ?, ?, ?)");
                preparedStatement.setInt(1, childId);
                preparedStatement.setString(2, txtParentName.getText());
                preparedStatement.setString(3, txtChildSurname.getText());
                preparedStatement.setString(4, (String) cBoxGender.getSelectedItem());
                preparedStatement.setString(5, fTxtPhone.getText());
                preparedStatement.executeUpdate();
                MainScreen.connection.commit();
                
                JOptionPane.showMessageDialog(this, "Kayıt başarıyla oluşturuldu", "Çocuk Ekleme", JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(this, "triggerIncreaseSizeOfClass triggerı çalıştı ve ilgili sınıf mevcudu bir arttırıldı.", "Trigger Mesajı", JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(this, "triggerRelationshipType triggerı çalıştı ve yakınlık derecesi eklendi.", "Trigger Mesajı", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e){
            try {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                MainScreen.connection.rollback();
            } catch (SQLException ex) {
                Logger.getLogger(AddEnrollmentScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }finally{
            try {
                MainScreen.connection.setAutoCommit(true);
            } catch (SQLException ex) {
                Logger.getLogger(AddEnrollmentScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lblChildName = new javax.swing.JLabel();
        lblChildSurname = new javax.swing.JLabel();
        lblBirthdate = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblParentName = new javax.swing.JLabel();
        txtChildName = new javax.swing.JTextField();
        txtChildSurname = new javax.swing.JTextField();
        txtParentName = new javax.swing.JTextField();
        btnAddEnrollment = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cBoxGender = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        lblEnrollmentType = new javax.swing.JLabel();
        lblPaymentType = new javax.swing.JLabel();
        cBoxPaymentType = new javax.swing.JComboBox<>();
        cBoxEnrollmentType = new javax.swing.JComboBox<>();
        fTxtBirthdate = new javax.swing.JFormattedTextField();
        lblEnrollmentType1 = new javax.swing.JLabel();
        lblPriceInfo = new javax.swing.JLabel();
        fTxtPhone = new javax.swing.JFormattedTextField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Kayıt Ekleme");
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);

        lblChildName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChildName.setText("İsim");

        lblChildSurname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChildSurname.setText("Soyisim");

        lblBirthdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBirthdate.setText("Doğum Tarihi");

        lblGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGender.setText("Cinsiyet");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhone.setText("Telefon");

        lblParentName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblParentName.setText("İsim");

        btnAddEnrollment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddEnrollment.setText("Kayıt Ekle");
        btnAddEnrollment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddEnrollmentMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Veli");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Öğrenci");

        cBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek", "Kadın" }));
        cBoxGender.setSelectedIndex(1);

        btnBack.setText("Geri");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMousePressed(evt);
            }
        });

        lblEnrollmentType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEnrollmentType.setText("Kayıt Türü");

        lblPaymentType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPaymentType.setText("Ödeme Türü");

        cBoxPaymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peşin", "Taksit" }));

        cBoxEnrollmentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tam Gün", "Yarım Gün" }));
        cBoxEnrollmentType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cBoxEnrollmentTypeİtemStateChanged(evt);
            }
        });

        try {
            fTxtBirthdate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblEnrollmentType1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEnrollmentType1.setText("Fiyat");

        lblPriceInfo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPriceInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        try {
            fTxtPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblChildName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChildSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEnrollmentType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPaymentType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtChildName, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtChildSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(cBoxPaymentType, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cBoxEnrollmentType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fTxtBirthdate))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(lblParentName, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(lblEnrollmentType1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtParentName, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(cBoxGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPriceInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fTxtPhone))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblParentName)
                                .addGap(137, 137, 137))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblChildName)
                                        .addGap(42, 42, 42)
                                        .addComponent(lblChildSurname))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtChildName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtChildSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblGender)
                                            .addComponent(cBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBirthdate)
                                    .addComponent(fTxtBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhone)
                                    .addComponent(fTxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnrollmentType)
                            .addComponent(cBoxEnrollmentType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnrollmentType1)
                            .addComponent(lblPriceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtParentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaymentType)
                    .addComponent(cBoxPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnAddEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMousePressed
        setVisible(false);
        MainScreen m = new MainScreen();
        m.setVisible(true);
    }//GEN-LAST:event_btnBackMousePressed

    private void btnAddEnrollmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddEnrollmentMousePressed
        addEnrollment();
    }//GEN-LAST:event_btnAddEnrollmentMousePressed
    
    public void changeLblPriceInfo(){
        try{
            String selectedEnrollmentType = (String) cBoxEnrollmentType.getSelectedItem();
            PreparedStatement preparedStatement = MainScreen.connection.prepareStatement("SELECT price FROM enrollmentPrice WHERE type = ?");
            preparedStatement.setString(1, selectedEnrollmentType);
            ResultSet resultSet = preparedStatement.executeQuery();
            while(resultSet.next()){
                lblPriceInfo.setText(String.format("%7.2f", resultSet.getFloat(1)));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cBoxEnrollmentTypeİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cBoxEnrollmentTypeİtemStateChanged
        changeLblPriceInfo();
    }//GEN-LAST:event_cBoxEnrollmentTypeİtemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEnrollmentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEnrollmentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEnrollmentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEnrollmentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEnrollmentScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEnrollment;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cBoxEnrollmentType;
    private javax.swing.JComboBox<String> cBoxGender;
    private javax.swing.JComboBox<String> cBoxPaymentType;
    private javax.swing.JFormattedTextField fTxtBirthdate;
    private javax.swing.JFormattedTextField fTxtPhone;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblChildName;
    private javax.swing.JLabel lblChildSurname;
    private javax.swing.JLabel lblEnrollmentType;
    private javax.swing.JLabel lblEnrollmentType1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblParentName;
    private javax.swing.JLabel lblPaymentType;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPriceInfo;
    private javax.swing.JTextField txtChildName;
    private javax.swing.JTextField txtChildSurname;
    private javax.swing.JTextField txtParentName;
    // End of variables declaration//GEN-END:variables
}
