package kresbilgisistemi;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EmircanKirez
 */
public class ListStudentAndParentScreen extends javax.swing.JFrame {
    DefaultTableModel model;
   
    public ListStudentAndParentScreen() {
        initComponents();
    }
    
    
    public void populate(){
        model = (DefaultTableModel)tableChildInfo.getModel();
        model.setRowCount(0);
        try{
            PreparedStatement preparedStatement;
            ResultSet resultSet;
            if(cBoxParent.getSelectedItem().equals("")){
                preparedStatement = MainScreen.connection.prepareStatement("SELECT * FROM childInformation WHERE age = ?");
                preparedStatement.setInt(1, Integer.valueOf((String) cBoxAge.getSelectedItem()));
                resultSet = preparedStatement.executeQuery();
            }else{
                preparedStatement = MainScreen.connection.prepareStatement("SELECT * FROM(SELECT * " +
                                                                "FROM childInformation " + 
                                                                "WHERE age = ? " +
                                                                "INTERSECT " +
                                                                "SELECT child.id, child.fname, child.lname, EXTRACT(YEAR FROM age(current_date, birthdate)) AS age, enrollmentType, price, paymentType " +
                                                                "FROM child, parent, enrollment, enrollmentPrice " +
                                                                "WHERE id = parent.childId AND id = enrollment.childId AND enrollmentType = type AND relationship = ?) AS tmp " + 
                                                                "ORDER BY tmp.id");
                preparedStatement.setInt(1, Integer.valueOf((String) cBoxAge.getSelectedItem()));
                preparedStatement.setString(2, (String) cBoxParent.getSelectedItem());
                resultSet = preparedStatement.executeQuery();
            }
            
            Object[] row = new Object[7];
            while(resultSet.next()){
                for (int i = 0; i < 7; i++){
                    row[i] = resultSet.getObject(i+1);
                }
                model.addRow(row);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
       
        tableChildInfo.setModel(model);
    };


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableChildInfo = new javax.swing.JTable();
        cBoxAge = new javax.swing.JComboBox<>();
        cBoxParent = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Öğrenci Bilgileri");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        tableChildInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "İsim", "Soyisim", "Yaş", "Kayıt Türü", "Kayıt Ücreti", "Ödeme Türü"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableChildInfo);
        if (tableChildInfo.getColumnModel().getColumnCount() > 0) {
            tableChildInfo.getColumnModel().getColumn(0).setResizable(false);
            tableChildInfo.getColumnModel().getColumn(1).setResizable(false);
            tableChildInfo.getColumnModel().getColumn(2).setResizable(false);
            tableChildInfo.getColumnModel().getColumn(3).setResizable(false);
            tableChildInfo.getColumnModel().getColumn(4).setResizable(false);
            tableChildInfo.getColumnModel().getColumn(5).setResizable(false);
            tableChildInfo.getColumnModel().getColumn(6).setResizable(false);
        }

        cBoxAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5" }));

        cBoxParent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anne", "Baba", "" }));
        cBoxParent.setSelectedIndex(2);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(" ");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnShow.setText("Göster");
        btnShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnShowMousePressed(evt);
            }
        });

        btnBack.setText("Geri");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMousePressed(evt);
            }
        });

        lblInfo.setText("Sadece yaşa göre filtrelemek isterseniz ebeveyn kutucuğunu boş bırakın!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnBack)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cBoxAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cBoxParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnShow)
                .addGap(30, 30, 30))
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cBoxAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(cBoxParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfo))))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMousePressed
        populate();
        if(cBoxParent.getSelectedItem().equals("")){
            lblTitle.setText(cBoxAge.getSelectedItem()+" Yaşındaki Çocukların Bilgileri");
        }
        else {
            lblTitle.setText("Sistemde Ebeveyni "+cBoxParent.getSelectedItem()+" Olan "+cBoxAge.getSelectedItem()+" Yaşındaki Çocukların Bilgileri");
        }

    }//GEN-LAST:event_btnShowMousePressed

    private void btnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMousePressed
        setVisible(false);
        MainScreen main = new MainScreen();
        main.setVisible(true);
    }//GEN-LAST:event_btnBackMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListStudentAndParentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListStudentAndParentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListStudentAndParentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListStudentAndParentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListStudentAndParentScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnShow;
    private javax.swing.JComboBox<String> cBoxAge;
    private javax.swing.JComboBox<String> cBoxParent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tableChildInfo;
    // End of variables declaration//GEN-END:variables
}
