package kresbilgisistemi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author EmircanKirez
 */
public class MainScreen extends javax.swing.JFrame {
    public static Connection connection;
    private String url = "jdbc:postgresql://localhost:5432/XYZKresi";
    private String user = "postgres";
    private String password = "231504";
    
    /**
     * Creates new form Main
     */
    public MainScreen() {
        getConnection();
        initComponents();
        
    }
    
    public void getConnection(){
        try{
            connection = DriverManager.getConnection(url, user, password);
        }catch(SQLException sqle){
            JOptionPane.showMessageDialog(this, sqle.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(-1);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuEnrollment = new javax.swing.JMenu();
        mItemAddEnrollment = new javax.swing.JMenuItem();
        mItemDeleteEnrollment = new javax.swing.JMenuItem();
        menuParent = new javax.swing.JMenu();
        mItemUpdatePhoneNumber = new javax.swing.JMenuItem();
        menuTeacher = new javax.swing.JMenu();
        mItemAddTeacher = new javax.swing.JMenuItem();
        mItemDeleteTeacher = new javax.swing.JMenuItem();
        menuStudent = new javax.swing.JMenu();
        mItemStudentInfo = new javax.swing.JMenuItem();
        menuKindergarten = new javax.swing.JMenu();
        mItemKindergartenInfo = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem5.setText("jMenuItem5");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XYZ Kreşi");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kresbilgisistemi/img/kindergarten.png"))); // NOI18N

        menuBar.setBackground(new java.awt.Color(255, 153, 153));

        menuEnrollment.setText("Kayıt İşlemleri");

        mItemAddEnrollment.setText("Kayıt Ekle");
        mItemAddEnrollment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mItemAddEnrollmentMousePressed(evt);
            }
        });
        menuEnrollment.add(mItemAddEnrollment);

        mItemDeleteEnrollment.setText("Kayıt Sil");
        mItemDeleteEnrollment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mItemDeleteEnrollmentMousePressed(evt);
            }
        });
        menuEnrollment.add(mItemDeleteEnrollment);

        menuBar.add(menuEnrollment);

        menuParent.setText("Veli İşlemleri");

        mItemUpdatePhoneNumber.setText("Telefon Numarası Güncelleme");
        mItemUpdatePhoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mItemUpdatePhoneNumberMousePressed(evt);
            }
        });
        menuParent.add(mItemUpdatePhoneNumber);

        menuBar.add(menuParent);

        menuTeacher.setText("Öğretmen İşlemleri");

        mItemAddTeacher.setText("Öğretmen Ekle");
        mItemAddTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mItemAddTeacherMousePressed(evt);
            }
        });
        menuTeacher.add(mItemAddTeacher);

        mItemDeleteTeacher.setText("Öğretmen Sil");
        mItemDeleteTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mItemDeleteTeacherMousePressed(evt);
            }
        });
        menuTeacher.add(mItemDeleteTeacher);

        menuBar.add(menuTeacher);

        menuStudent.setText("Öğrenci İşlemleri");

        mItemStudentInfo.setText("Öğrenci Bilgileri");
        mItemStudentInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mItemStudentInfoMousePressed(evt);
            }
        });
        menuStudent.add(mItemStudentInfo);

        menuBar.add(menuStudent);

        menuKindergarten.setText("Kreş Hakkında");

        mItemKindergartenInfo.setText("Kreş Bilgileri");
        mItemKindergartenInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mItemKindergartenInfoMousePressed(evt);
            }
        });
        menuKindergarten.add(mItemKindergartenInfo);

        menuBar.add(menuKindergarten);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mItemAddEnrollmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mItemAddEnrollmentMousePressed
        AddEnrollmentScreen addEnrollment = new AddEnrollmentScreen();
        setVisible(false);
        addEnrollment.setVisible(true);
    }//GEN-LAST:event_mItemAddEnrollmentMousePressed

    private void mItemUpdatePhoneNumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mItemUpdatePhoneNumberMousePressed
        UpdateParentInfoScreen updateParentInfo = new UpdateParentInfoScreen();
        setVisible(false);
        updateParentInfo.setVisible(true);
    }//GEN-LAST:event_mItemUpdatePhoneNumberMousePressed

    private void mItemKindergartenInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mItemKindergartenInfoMousePressed
        KindergartenInfoScreen kindergartenInfoScreen = new KindergartenInfoScreen();
        setVisible(false);
        kindergartenInfoScreen.setVisible(true);
    }//GEN-LAST:event_mItemKindergartenInfoMousePressed

    private void mItemDeleteTeacherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mItemDeleteTeacherMousePressed
        DeleteTeacherScreen deleteTeacher = new DeleteTeacherScreen();
        setVisible(false);
        deleteTeacher.setVisible(true);
    }//GEN-LAST:event_mItemDeleteTeacherMousePressed

    private void mItemStudentInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mItemStudentInfoMousePressed
        ListStudentAndParentScreen listStudentAndParentScreen = new ListStudentAndParentScreen();
        setVisible(false);
        listStudentAndParentScreen.setVisible(true);
    }//GEN-LAST:event_mItemStudentInfoMousePressed

    private void mItemDeleteEnrollmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mItemDeleteEnrollmentMousePressed
        DeleteEnrollmentScreen deleteEnrollment = new DeleteEnrollmentScreen();
        setVisible(false);
        deleteEnrollment.setVisible(true);
    }//GEN-LAST:event_mItemDeleteEnrollmentMousePressed

    private void mItemAddTeacherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mItemAddTeacherMousePressed
        AddTeacherScreen addTeacherScreen = new AddTeacherScreen();
        setVisible(false);
        addTeacherScreen.setVisible(true);
    }//GEN-LAST:event_mItemAddTeacherMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem mItemAddEnrollment;
    private javax.swing.JMenuItem mItemAddTeacher;
    private javax.swing.JMenuItem mItemDeleteEnrollment;
    private javax.swing.JMenuItem mItemDeleteTeacher;
    private javax.swing.JMenuItem mItemKindergartenInfo;
    private javax.swing.JMenuItem mItemStudentInfo;
    private javax.swing.JMenuItem mItemUpdatePhoneNumber;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEnrollment;
    private javax.swing.JMenu menuKindergarten;
    private javax.swing.JMenu menuParent;
    private javax.swing.JMenu menuStudent;
    private javax.swing.JMenu menuTeacher;
    // End of variables declaration//GEN-END:variables
}
